version: 0.2

phases:
  install:
    # https://github.com/aws/aws-codebuild-docker-images/issues/490#issuecomment-976470059
    runtime-versions:
      nodejs: 16
    commands:
      - n 16
  pre_build:
    commands:
      - echo Starting npm install
      - npm i
  build:
    commands:
      - echo Starting npm build
artifacts:
  files:
    - package.json
    - package-lock.json
    - node_modules/**/*
